src/main/java/com/liberty52/product/service/applicationservice/ProductIntroductionCreateService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/ProductIntroductionCreateServiceImpl.java, src/main/java/com/liberty52/product/service/controller/ProductIntroductionCreateController.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/test/java/com/liberty52/product/service/applicationservice/mock/ProductIntroductionCreateMockTest.java
Closes #223
***
-  상품 소개 관리 추가
```
POST  admin/product/{productId}/introduction
Status: 
201: 추가 성공
404: productId에 해당하는 Product가 없음
Request Header: {
Authorization: access_token
}
{
"productId" : String,
"imageFile": MultipartFile
}
``` 
**CODE** 
***
***
- 관리자 서비스를 인스턴스로 따로 나누지 말고 병합하는게 어떤지
- API를 수기로 작성 및 수정하지 말고 Swagger나 Rest Doc 을 쓰는게 어떤지
=> (관리자) 상품 소개 관리 추가

src/main/java/com/liberty52/product/service/applicationservice/ProductIntroductionModifyService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/ProductIntroductionModifyServiceImpl.java, src/main/java/com/liberty52/product/service/controller/ProductIntroductionModifyController.java, src/test/java/com/liberty52/product/service/applicationservice/mock/ProductIntroductionModifyMockTest.java
***
상품 소개 관리 수정 API 및 테스트코드 작성
**API**
```
PATCH admin/product/{productId}/introduction
REQUEST 
Headers: {
LB-Role: role
}
Data: {
"images": MultipartFile (required = false)
}
RESPONSE
Status: 
204: 수정 성공
404: productId에 해당하는 Product가 없음
```
**CODE** 
***
***
우선 박찬길 팀원과 상의해서 요청 데이터는 사진 1장으로 결정, 텍스트 & 사진 여러장으로 변경할지에 대해서는 향후 추가적으로 의논 후에 수정하는 방향으로 결정했습니다.
=> (관리자) 상품 소개 관리 수정

src/main/java/com/liberty52/product/global/config/DBInitConfig.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailCreateServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailModifyServiceImpl.java, src/main/java/com/liberty52/product/service/controller/dto/CreateOptionDetailRequestDto.java, src/main/java/com/liberty52/product/service/controller/dto/OptionDetailModifyRequestDto.java, src/main/java/com/liberty52/product/service/controller/dto/ProductOptionDetailResponseDto.java, src/main/java/com/liberty52/product/service/entity/OptionDetail.java, src/test/java/com/liberty52/product/service/applicationservice/OptionDetailModifyServiceTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemSchedulerServiceMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/OptionDetailModifyServiceMockTest.java, src/test/java/com/liberty52/product/service/utils/MockFactory.java
***
**API**
```
PUT /admin/optionDetail/{optionDetailId}
>> REQUEST
headers:
LB-Role: role
<<
data(JSON)
{
"name": String
"price": Integer
"onSale": Boolean
"stock" : Integer
}
status
200 ok - 삭제 성공
400 BadRequest - 잘못된 요청 (유효하지 않은 optionDetailId로 요청한 경우 등)
401 Unauthorized - 인증 실패 (로그인을 하지 않은 경우 등)
403 Forbidden - 인가 실패 (관리자가 아닌 계정으로 요청한 경우 등)
<<
```
***
***
1. 재고량만 따로 수정하는 api가 아닌 기존 상품 옵션 선택지 수정 api에 재고량 항목을 추가하는 방식으로 구현했습니다.
2. 상품 옵션 선택지 필드를 OptionDetail 엔티티에 추가해서 기존에 존재하던 관련된 CRUD 코드들을 모두 일부 수정했습니다.(관련된 API 문서는 모두 이에 맞춰 수정했어요)
3. buider 패턴 사용할 수 있는 상황이면 가급적 .create 말고 builder 패턴으로 객체 생성하면 좋을것 같습니다! 유연성을 높여 요청 데이터를 추가할 때  테스트 코드부터 실제 서비스 코드까지 많은  부분을 수정해야하는 상황을 줄일 수 있을것 같습니다.
=> [관리자] 상품 옵션 선택지 재고량 수정 기능

src/main/java/com/liberty52/product/global/adapter/ImageUpscaler.java, src/main/java/com/liberty52/product/global/adapter/StableDiffusionApi.java, src/main/java/com/liberty52/product/global/util/Result.java, src/main/java/com/liberty52/product/service/applicationservice/ImageUpscalingService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImpl.java, src/main/java/com/liberty52/product/service/controller/ImageUpscalingController.java, src/main/java/com/liberty52/product/service/controller/dto/ImageUpscalingDto.java, src/test/java/com/liberty52/product/global/adapter/StableDiffusionApiTest.java, src/test/java/com/liberty52/product/global/adapter/imageupscaler/StableDiffusionApiTest.java, src/test/java/com/liberty52/product/service/applicationservice/impl/ImageUpscalingServiceImplTest.java, src/test/java/com/liberty52/product/service/controller/ImageUpscalingControllerTest.java
[Base requirement](https://github.com/Liberty52/config-file-repository/issues)
[Stable-Diffusion upscaler API](https://stablediffusionapi.com/docs/image-editing/super-resolution)
***
나중에 `ImageUpscaler` 구현체가 바뀔 수도 있을 거 같아서 인터페이스로 뺐습니다.
**API**
#256 
***
API 동작 확인
- before 1920x1263
- after 3840x2526
https://pub-3626123a908346a7a8be8d9295f44e26.r2.dev/generations/beaf9680-2bb8-4f40-a226-6b3b51f77b19_out.png
사진이 너무 큰지 안 뜨네요
***
=> feat:관리자는 이미지를 업스케일(upscaling)한다.

src/main/java/com/liberty52/product/global/config/BeanConfig.java, src/main/java/com/liberty52/product/global/config/JacksonConfig.java, src/main/java/com/liberty52/product/service/entity/payment/VBankPayment.java
Resolve #262 
***
ObjectMapper에 기본 생성자가 없어도 역직렬화 가능하게 해주는 `ParameterNamesModule` 추가
**AS-IS**
```java
@Bean
public ObjectMapper objectMapper() {
ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JavaTimeModule());
mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
return mapper;
}
```
**TO-BE**
```java
@Bean
public ObjectMapper objectMapper() {
ObjectMapper mapper = new ObjectMapper();
mapper.registerModules(
new JavaTimeModule(),
new ParameterNamesModule()
);
mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
return mapper;
}
```
=> fix: ObjectMapper 기본생성자 요구 모듈 추가

build.gradle, src/main/java/com/liberty52/product/global/annotation/DistributedLock.java, src/main/java/com/liberty52/product/global/aspect/DistributedLockAspect.java, src/main/java/com/liberty52/product/global/aspect/DistributedLockTransaction.java, src/main/java/com/liberty52/product/global/config/AspectConfig.java, src/main/java/com/liberty52/product/global/config/RedisConfig.java, src/main/java/com/liberty52/product/global/event/events/OrderFailedPayRollbackEvent.java, src/main/java/com/liberty52/product/global/event/handler/OrderFailedPayRollbackEventHandler.java, src/main/java/com/liberty52/product/global/exception/external/badrequest/DistributedLockException.java, src/main/java/com/liberty52/product/global/util/CustomSpringELParser.java, src/main/java/com/liberty52/product/global/util/Result.java, src/main/java/com/liberty52/product/service/applicationservice/OptionDetailMultipleStockManageService.java, src/main/java/com/liberty52/product/service/applicationservice/OptionDetailStockManageService.java, src/main/java/com/liberty52/product/service/applicationservice/OrderFailedPayRollbackService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OptionDetailStockManageServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OrderFailedPayRollbackServiceImpl.java, src/main/java/com/liberty52/product/service/entity/OptionDetail.java, src/main/resources/application.yml, src/test/java/com/liberty52/product/service/applicationservice/impl/OptionDetailStockManageServiceImplTest.java, src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java, src/test/java/com/liberty52/product/service/utils/MockFactory.java
Resolve #269 
***
1. 단건 주문, 장바구니 복수건 주문 등에서 발생하는 재고량 감소 시 데이터 접근에 대해 Redisson으로 락을 설정
2. 카드결제 주문 실패(위조 결제 등) 시 재고량을 롤백시키기 위한 이벤트 발행 및 컨슘 서비스 추가
각 옵션 디테일 별로 재고량을 확인하여 더티 커밋 등의 문제를 해결하기 위해  
옵션 디테일의 재고를 관리하기 위한 `OptionDetailStockManageService`를 생성하여  
해당 서비스 클래스 안에서 `@DistributedLock`을 이용하여 분산락을 구현하였습니다.
분산락과 관련된 기능들은 `global.annotation.DistributedLock`과 `global.aspect.DistributedLockAspect`에 구현하였습니다.
***
***
@jinlee0 
> `Result<T>` 클래스와 관련하여 `runCatching()` 시 발생된 RuntimeException을 그대로  발생시키기 위해 `getOrThrows()` 인터페이스를 추가하였고, `Failure<T>` 클래스의 `runtimeException` 프로퍼티 추가 및 생성자에서 인자로 받은 `Throwable`을 RuntimeException으로 캐스팅하여 설정하도록 하였습니다.
임의로 추가해보았는데 컨펌 부탁드릴게요. :) 
@ImKunYoung 
> Redis의 설정을 모두 클라우드 환경의 레디스로 물리게끔 하고자 합니다. 로컬 프로파일에도 설정을 추가하면 모든 개발자들의 로컬에도 레디스가 운영되어 있어야 하는 문제가 예상되어서 이처럼 하고자 하는데, 의견 …
=> 재고량 감소 비동기 데이터 정합성 보장

src/main/java/com/liberty52/product/global/config/DBInitConfig.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java, src/main/java/com/liberty52/product/service/controller/dto/OrderCreateRequestDto.java, src/test/java/com/liberty52/product/service/applicationservice/OrderCreateServiceImplTest.java, src/test/java/com/liberty52/product/service/applicationservice/impl/CanceledOrderRetrieveTest.java, src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java, src/test/java/com/liberty52/product/service/entity/OrdersEntityTest.java
Resolve #284 
***
**API**
- Request Body에서 `options` -> `optionDetailIds`로 수정.
- API docs. (WIKI)에도 수정 반영 https://github.com/Liberty52/Liberty52/wiki/PRODUCT-API
AS-IS
```
{
"dto": {
"productDto": {
...
"options": string[],    // 옵션 이름 배열
...
},
...
}
```
TO-BE
```
{
"dto": {
"productDto": {
...
"optionDetailIds": string[],    // 옵션 디테일 아이디 배열
...
},
...
}
```
**CODE** 
옵션 디테일 fetch code 수정
AS-IS
```java
List<String> optionDetailIds = dto.getProductDto().getOptions().stream()
//TODO option detail 조회를 id로 변경되면, 179 - 182를 합칠 수 있음.
.map(optionName -> optionDetailRepository.findByName(optionName)
.orElseThrow(() -> new ResourceNotFoundException(RESOURCE_NAME_OPTION_DETAIL, PARAM_NAME_OPTION_DETAIL_NAME, optionName)))
.map(OptionDetail::getId)
// ..중략..
```
TO-BE
```java
List<String> …
```
=> 주문 요청 시 옵션명이 아닌 옵션 ID로 요청하도록 API 수정

src/main/java/com/liberty52/product/global/config/DBInitConfig.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/test/java/com/liberty52/product/service/applicationservice/CartItemRemoveServiceImplTest.java, src/test/java/com/liberty52/product/service/applicationservice/ReviewCreateServiceImplTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemCreateServiceMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemRetrieveServiceMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/CartItemSchedulerServiceMockTest.java, src/test/java/com/liberty52/product/service/utils/MockFactory.java
***
Product 엔티티에 boolean 타입의 isCustom필드 추가 (true => 작가 라이선스 이미지 사용 불가&개인 이미지 회사 이벤트 라이선스 이미지 사용 및 커스텀 가능, false => 작가 라이선스 이미지 사용 가능(편집 불가))
연관된 테스트코드, DBInit에도 해당 필드 추가 세팅
***
All test passed
=> Product 엔티티 - 라이선스 적용 상품인지 구분 위한 isCustom 속성 추가

build.gradle, src/main/java/com/liberty52/product/global/config/BeanConfig.java, src/main/java/com/liberty52/product/service/applicationservice/ProductCreateService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/ProductCreateServiceImpl.java, src/main/java/com/liberty52/product/service/controller/ProductController.java, src/main/java/com/liberty52/product/service/controller/ProductInfoController.java, src/main/java/com/liberty52/product/service/controller/dto/ProductRequestDto.java, src/main/java/com/liberty52/product/service/controller/dto/ProductResponseDto.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/ProductState.java, src/test/java/com/liberty52/product/service/applicationservice/mock/ProductCreateServiceMockTest.java, src/test/java/com/liberty52/product/service/controller/ProductControllerTest.java
***
상품 추가 기능 구현, 추가시 상품 사진도 함께 등록 가능하도록 구현
커스텀 상품인지, 라이선스 이미지 전용 상품인지 구분하는 필드 추가(isCustom)
**API**
```
POST admin/product
>> REQUEST 
Headers: {
LB-Role: role
}
image : {
MultipartFile (required = false) //상품 사진
}
data (Content-type : application/json): { 
"name" : String(Not Blank), //상품명
"productState" : String(Not Blank), //상품 상태(Enum : "ON_SALE" or "NOT_SALE")
"price" : Long(Min:0), //상품 가격
"isCustom" : Boolean(Not Null) //커스텀 상품인지(true), 라이선스 이미지 전용 상품인지(false)
}
<<
>> RESPONSE
Status: 
201: 생성 성공
400: 잘못된 요청 데이터로 요청
415: data 요청 Content-type을 application/json로 요청하지 않는 등 잘못된 요청 타입으로 요청시 발생하는 에러
Data:
{
"id": "647c573f-2e36-4240-9c7a-c614577884eb",
"name": "TestProduct",
"productState": "NOT_SALE",
"price": 100,
"custom": true
}
<<
```
Postman API 요청 예시
***
***
=> [관리자] 상품 추가

src/main/java/com/liberty52/product/service/applicationservice/impl/OrderRetrieveServiceImpl.java, src/main/java/com/liberty52/product/service/controller/dto/AdminCanceledOrderListResponse.java, src/main/java/com/liberty52/product/service/controller/dto/AdminOrderListResponse.java, src/main/java/com/liberty52/product/service/controller/dto/OrderDeliveryDto.java, src/main/java/com/liberty52/product/service/controller/dto/OrderDetailRetrieveResponse.java, src/main/java/com/liberty52/product/service/controller/dto/OrdersRetrieveResponse.java, src/main/java/com/liberty52/product/service/entity/Orders.java, src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepositoryImpl.java, src/test/java/com/liberty52/product/service/applicationservice/impl/OrderRetrieveServiceImplTest.java, src/test/java/com/liberty52/product/service/controller/OrderControllerTest.java, src/test/java/com/liberty52/product/service/repository/OrdersTest.java
Resolve #306 
***
기존 유저 및 관리자의 주문 상세정보 조회 API의 응답값에 주문배송정보(`orderDelivery`) 프로퍼티를 추가하였습니다.
또한, `OrderRetrieveService`에 대한 단위 테스트코드가 없어서 추가하였습니다.
***
***
=> 주문 정보 조회 시 주문배송정보(택배사코드, 택배사이름, 운송장번호) 반환 추가

src/main/java/com/liberty52/product/global/adapter/portone/PortOneRequestClient.java, src/main/java/com/liberty52/product/global/adapter/portone/config/PortOneWebClientFactory.java, src/main/java/com/liberty52/product/global/config/BeanConfig.java, src/test/java/com/liberty52/product/ProductApplicationTests.java
Resolve #313 
***
`PortOne`에서 사용하는 WebClient 빈이 `global.config.BeanConfig` 안에서 초기화하였는데, 
이 때문에 다른 WebClient 빈을 바로 사용하기에 제약이 발생할 것으로 예상된다. 
따라서 이를 `adapter.portone.config.PortOneWebClientFactory`라는 설정 클래스로 이관하였다.
***
***
=> refactor: PortOne WebClient 빈 위치 변경

src/main/java/com/liberty52/product/ProductApplication.java, src/main/java/com/liberty52/product/global/config/FeignClientConfig.java, src/main/java/com/liberty52/product/global/config/SchedulerConfig.java
Resolve #315 
***
Main 클래스의 어노테이션으로 설정되어 있는 여러 configuration을 각 config 클래스로 이관
***
***
=> refactor: Main 클래스 configuration 어노테이션 분리

src/main/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImpl.java, src/main/java/com/liberty52/product/service/entity/OrderDelivery.java, src/test/java/com/liberty52/product/service/applicationservice/impl/OrderDeliveryServiceImplTest.java
Resolve #333 
***
문제: 주문배송정보 (배송시작 시 등록하는 운송장번호) 추가 시 중복체크를 하지 않음에 따라 중복 저장하게 된다.
해결: 수정 API를 별도로 구현하지는 않고, 추가(등록) API 호출 시 주문배송정보가 존재할 경우 수정하도록 하였다.
=> hotfix: 주문배송정보 추가 시 중복추가 문제 해결

src/main/java/com/liberty52/product/service/applicationservice/ProductDeliveryOptionService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/ProductDeliveryOptionServiceImpl.java, src/main/java/com/liberty52/product/service/controller/ProductInfoController.java, src/main/java/com/liberty52/product/service/controller/dto/AdminProductDeliveryOptionsDto.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/ProductDeliveryOption.java, src/test/java/com/liberty52/product/service/applicationservice/impl/ProductDeliveryOptionServiceImplTest.java, src/test/java/com/liberty52/product/service/controller/ProductInfoControllerTest.java, src/test/java/com/liberty52/product/service/utils/MockFactory.java
Resolve #328 
***
상품별 택배사이름 및 배송비를 등록, 조회, 수정할 수 있는 기능을 추가하였습니다.
**API**
명세는 #328 을 참고해주세요. API 명세서 추가 예정입니다.
***
<br>
<br>
***
=> [관리자] 상품별 택배사/배송비 관련 API 추가

src/main/java/com/liberty52/product/service/applicationservice/LicenseOptionCreateService.java, src/main/java/com/liberty52/product/service/applicationservice/LicenseOptionDetailCreateService.java, src/main/java/com/liberty52/product/service/applicationservice/LicenseOptionDetailModifyService.java, src/main/java/com/liberty52/product/service/applicationservice/LicenseOptionModifyService.java, src/main/java/com/liberty52/product/service/applicationservice/LicenseProductInfoRetrieveService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailCreateServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailModifyServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionModifyServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseProductInfoRetrieveServiceImpl.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionCreateRequestDto.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailCreateDto.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailInfoResponseDto.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailModifyDto.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionInfoResponseDto.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionModifyRequestDto.java, src/main/java/com/liberty52/product/service/controller/license/LicenseOptionController.java, src/main/java/com/liberty52/product/service/controller/license/LicenseOptionDetailController.java, src/main/java/com/liberty52/product/service/controller/license/LicenseProductInfoController.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java, src/main/java/com/liberty52/product/service/entity/license/LicenseOptionDetail.java, src/main/java/com/liberty52/product/service/repository/LicenseOptionDetailRepository.java, src/main/java/com/liberty52/product/service/repository/LicenseOptionRepository.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionCreateMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailCreateMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailModifyMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionModifyMockTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseProductInfoRetrieveMockTest.java
***
- 라이선스 상품 옵션 생성
- 라이선스 상품 옵션 수정
- 라이선스 상품 옵션 조회
API 문서에 업데이트 예정입니다.
***
***
- 추후에 라이선스 상품 구매 시 수량 동기화 관련(분산락) 로직 추가 예정입니다.
=> [관리자] 라이선스 상품 옵션 CRUD

src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionCreateServiceImpl.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionCreateMockTest.java
- LicenseOption 생성 시 `save()` 를 해서 이미 저장했는데 cascade 때문에 또 저장할려해서 문제 발생
- cascade 옵션을 Product entity에 주는 걸로 수정 및 생성 시 `save()` 삭제
=> 상품과 라이선스 옵션 간 cascade 설정 변경

src/main/java/com/liberty52/product/service/applicationservice/impl/LicenseOptionDetailModifyServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImpl.java, src/main/java/com/liberty52/product/service/applicationservice/impl/OrderStatusModifyServiceImpl.java, src/main/java/com/liberty52/product/service/controller/OrderController.java, src/main/java/com/liberty52/product/service/controller/dto/LicenseOptionDetailInfoResponseDto.java, src/main/java/com/liberty52/product/service/controller/dto/OrderDetailRetrieveResponse.java, src/main/java/com/liberty52/product/service/controller/dto/OrderRetrieveProductResponse.java, src/main/java/com/liberty52/product/service/controller/dto/OrdersRetrieveResponse.java, src/main/java/com/liberty52/product/service/controller/license/LicenseOptionDetailAdminController.java, src/main/java/com/liberty52/product/service/entity/CustomProduct.java, src/main/java/com/liberty52/product/service/entity/Orders.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/license/CustomLicenseOption.java, src/main/java/com/liberty52/product/service/entity/license/LicenseOption.java, src/main/java/com/liberty52/product/service/entity/license/LicenseOptionDetail.java, src/main/java/com/liberty52/product/service/repository/CustomLicenseOptionRepository.java, src/test/java/com/liberty52/product/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java, src/test/java/com/liberty52/product/service/applicationservice/mock/LicenseOptionDetailModifyMockTest.java, src/test/java/com/liberty52/product/service/utils/MockFactory.java
Resolve #351 
- 라이선스 상품 주문 생성
- 주문 목록 조회 시 isCustom필드 추가
- 가상계좌 입력시 은행 종류 제한 해제
- 라이선스 옵션 상세 수정 시 이미지만 따로 수정 가능
***
이슈 처리와 작업 PR를 따로 나눴어야 했는데 죄송합니다. 다음에는 꼭 분리하겠습니다!
=> 라이선스 상품 주문 생성

src/main/java/com/liberty52/product/service/applicationservice/impl/ProductRemoveServiceImpl.java, src/main/java/com/liberty52/product/service/entity/Product.java, src/main/java/com/liberty52/product/service/entity/ProductOption.java, src/main/java/com/liberty52/product/service/repository/CustomProductRepository.java
***
1. 상품을 삭제하면  커스텀 상품과 참조관계로 인해 삭제가 되지 않음 -> 양방향 관계설정으로 관리하려 했으나 관계 설정시 다른 코드 20곳 이상에서 오류가 발생 -> 삭제시 먼저 커스텀 상품을 삭제하고 상품 삭제하도록 변경
2.  상품을 삭제하면 상품옵션과 참조관계로 인해 삭제가 되지 않음 -> 동일한 문제 -> 기존에 양방향 관계 매핑 되어 있었어서 cascadetype.REMOVE 임시방편으로 추가
3.  상품을 삭제 -> 상품옵션을 먼저 삭제해야함 -> 옵션디테일과 참조관계로 인해 삭제가 되지 않음 -> 동일한 방법으로 해결
4. 옵션디테일 -> 커스텀 프로덕트 옵션과의 별도의 참조관계를 고려한 설정이 없어보여 마찬가지로 문제 발생이 예상되나 일단 두었음 
***
일단 로컬환경에서 눈에 보이는 문제들만 임시방편으로 막았습니다. 양방향 매핑시 참조 관계를 명확히 설정하지 않았거나 별도의 삭제 로직이 없을 시 이렇게 꼬리에 꼬리를 무는 형태로 또 문제가 분명 터질거 같습니다. 제가 다 바꾸기엔 범위가 너무 넓고 어떤 로직에 손상을 줄지 알 수 없어 당장 눈에 보이는 오류만 막았으니 나중에 시간적 여유가 있으면 이것에 대해 논의하면 좋을거 같습니다
=> 상품, 커스텀 상품 삭제관련 참조관계 설정 조정

src/main/java/com/liberty52/product/service/applicationservice/SalesRetrieveService.java, src/main/java/com/liberty52/product/service/applicationservice/impl/SalesRetrieveServiceImpl.java, src/main/java/com/liberty52/product/service/controller/SalesAdminController.java, src/main/java/com/liberty52/product/service/controller/dto/SalesRequestDto.java, src/main/java/com/liberty52/product/service/controller/dto/SalesResponseDto.java, src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepository.java, src/main/java/com/liberty52/product/service/repository/OrderQueryDslRepositoryImpl.java, src/test/java/com/liberty52/product/service/applicationservice/SalesRetrieveServiceImplTest.java
***
조건에 따라 매출액과 판매량을 동적 조회 (현재 적용된 조건은 기간, 제품명 -> 향후 다른 조건들 추가 가능)
**API**
```
GET /admin/sales
Request Header
{
"LB-Role" : accessToken,
}
Request Body
{
"startDate" : LocalDate (required = false)
"endDate" : LocalDate (required = false)
"productName" : String (required = false)
}
* 요청 예시
전체 기간에 대한 조회 : body없이 요청
상품별 조회 : productName만 명시해 요청
특정 기간 이후의 조회 : startDate만 명시해 요청
특정 기간 까지의 조회 : endDate만 명시해 요청
특정 기간 사이의 조회 : startDate, endDate 명시해 요청
...
Response Status : 200(성공), 400(잘못된 요청데이터 양식), 401(토큰 없음 - 비 로그인 상태 등), 403(권한 없음 - 관리자 아님 등)
Response Body
{
salesMoney : 매출액 (Long)
salesQuantity : 판매량 (Long)
}
``` 
**CODE** 
QueryDSL 사용
***
***
none
=> 매출액, 판매량 동적 조회

liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/LicenseOptionDetailStockManageService.java, liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/OptionDetailMultipleStockManageService.java, liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/LicenseOptionDetailStockManageServiceImpl.java, liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OptionDetailMultipleStockManageServiceImpl.java, liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImpl.java, liberty-main-service/src/main/java/com/liberty52/main/service/applicationservice/impl/OrderFailedPayRollbackServiceImpl.java, liberty-main-service/src/main/java/com/liberty52/main/service/entity/license/LicenseOptionDetail.java, liberty-main-service/src/test/java/com/liberty52/main/service/applicationservice/impl/OrderCreateServiceImplUnitTest.java
Resolve #366
***
- 라이선스 상품 구매
- 라이선스 장바구니 구매
- 라이선스 상품 주문 시 라이선스 옵션에서 해당 옵션의 재고 감소 (가상계좌, 카드)
- 라이선스 상품 카드 결제(재고량 감소 잘 됨)
- 라이선스 상품 가상 계좌 결제(재고량 감소 잘 됨)
- curl 명령어를 통한 동시성 처리도 잘 됨
***
=> 라이선스 상품 주문 관련 로직 변경
